package com.exam.service;

import com.exam.entity.ExamSession;
import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.WriterProperties;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.itextpdf.layout.properties.VerticalAlignment;
import org.springframework.stereotype.Service;

import java.io.OutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * INTEGRITY CERTIFICATE PDF GENERATOR — Purely additive.
 * Generates a professional audit certificate proving exam seating integrity.
 * Designed for NAAC/NBA compliance documentation.
 */
@Service
public class IntegrityCertificatePdfService {

    // Professional color scheme
    private static final DeviceRgb DARK_BLUE = new DeviceRgb(15, 23, 42);
    private static final DeviceRgb BRAND_BLUE = new DeviceRgb(79, 70, 229);
    private static final DeviceRgb SUCCESS_GREEN = new DeviceRgb(22, 163, 74);
    private static final DeviceRgb FAIL_RED = new DeviceRgb(220, 38, 38);
    private static final DeviceRgb LIGHT_BG = new DeviceRgb(248, 250, 252);
    private static final DeviceRgb BORDER_COLOR = new DeviceRgb(226, 232, 240);

    public void generateCertificate(IntegrityAuditService.AuditReport report, OutputStream outStream) {
        ExamSession session = report.batch().getExamSession();

        WriterProperties props = new WriterProperties().setFullCompressionMode(true);
        try (PdfWriter writer = new PdfWriter(outStream, props)) {
            writer.setCloseStream(false);
            PdfDocument pdf = new PdfDocument(writer);
            Document doc = new Document(pdf, PageSize.A4);
            doc.setMargins(40, 40, 40, 40);

            PdfFont bold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
            PdfFont regular = PdfFontFactory.createFont(StandardFonts.HELVETICA);
            PdfFont italic = PdfFontFactory.createFont(StandardFonts.HELVETICA_OBLIQUE);

            String dateStr = session.getExamDate().format(DateTimeFormatter.ofPattern("dd.MM.yyyy"));
            String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm:ss"));

            // ==================== HEADER ====================
            doc.add(new Paragraph("CONFIDENTIAL — EXAMINATION INTEGRITY DOCUMENT")
                    .setFont(bold).setFontSize(8).setFontColor(BRAND_BLUE)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(5));

            doc.add(new Paragraph(resolveCollegeName().toUpperCase())
                    .setFont(bold).setFontSize(14).setFontColor(DARK_BLUE)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(0));

            doc.add(new Paragraph("Office of the Controller of Examinations")
                    .setFont(regular).setFontSize(10).setFontColor(DARK_BLUE)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(3));

            // Horizontal rule
            Table hr = new Table(1).useAllAvailableWidth();
            hr.addCell(new Cell().setBorderBottom(new SolidBorder(BRAND_BLUE, 2))
                    .setBorderTop(Border.NO_BORDER).setBorderLeft(Border.NO_BORDER).setBorderRight(Border.NO_BORDER)
                    .setHeight(1));
            doc.add(hr);

            // ==================== CERTIFICATE TITLE ====================
            doc.add(new Paragraph("SEATING ARRANGEMENT INTEGRITY CERTIFICATE")
                    .setFont(bold).setFontSize(16).setFontColor(DARK_BLUE)
                    .setTextAlignment(TextAlignment.CENTER).setMarginTop(15).setMarginBottom(3));

            doc.add(new Paragraph("Automated Security Audit Report — Generated by HallSync Engine")
                    .setFont(italic).setFontSize(9).setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(15));

            // ==================== EXAM DETAILS BOX ====================
            Table examDetails = new Table(UnitValue.createPercentArray(new float[]{1, 1, 1})).useAllAvailableWidth();
            examDetails.setBackgroundColor(LIGHT_BG).setPadding(8)
                    .setBorder(new SolidBorder(BORDER_COLOR, 1));

            examDetails.addCell(detailCell("Examination", session.getName(), bold, regular));
            examDetails.addCell(detailCell("Date", dateStr, bold, regular));
            examDetails.addCell(detailCell("Session", session.getSession(), bold, regular));
            doc.add(examDetails);

            // ==================== VERDICT BANNER ====================
            DeviceRgb verdictColor = report.certified() ? SUCCESS_GREEN : FAIL_RED;
            String verdictText = report.certified()
                    ? "✓  INTEGRITY VERIFIED — ZERO SUBJECT ADJACENCY VIOLATIONS"
                    : "✗  INTEGRITY COMPROMISED — VIOLATIONS DETECTED";

            Table verdictBox = new Table(1).useAllAvailableWidth().setMarginTop(15);
            verdictBox.addCell(new Cell()
                    .add(new Paragraph(verdictText).setFont(bold).setFontSize(12).setFontColor(ColorConstants.WHITE)
                            .setTextAlignment(TextAlignment.CENTER))
                    .setBackgroundColor(verdictColor)
                    .setPadding(12)
                    .setBorder(Border.NO_BORDER));
            doc.add(verdictBox);

            // ==================== STATISTICS SUMMARY ====================
            doc.add(new Paragraph("AUDIT STATISTICS")
                    .setFont(bold).setFontSize(11).setFontColor(DARK_BLUE)
                    .setMarginTop(15).setMarginBottom(5));

            Table statsTable = new Table(UnitValue.createPercentArray(new float[]{3, 2})).useAllAvailableWidth();
            statsTable.setBorder(new SolidBorder(BORDER_COLOR, 1));

            addStatRow(statsTable, "Total Students Allocated", String.valueOf(report.totalStudents()), bold, regular);
            addStatRow(statsTable, "Total Examination Halls Used", String.valueOf(report.totalHalls()), bold, regular);
            addStatRow(statsTable, "Total Adjacency Checks Performed",
                    String.format("%,d", report.totalAdjacencyChecks()), bold, regular);
            addStatRow(statsTable, "Subject Adjacency Violations Found",
                    String.valueOf(report.totalAdjacencyViolations()), bold, regular);
            addStatRow(statsTable, "Subject Separation Score",
                    String.format("%.2f%%", report.integrityScorePercent()), bold, regular);
            addStatRow(statsTable, "Department Column Purity Score",
                    String.format("%.2f%%", report.deptPurityScorePercent()), bold, regular);

            doc.add(statsTable);

            // ==================== PER-HALL BREAKDOWN ====================
            doc.add(new Paragraph("HALL-WISE VERIFICATION DETAILS")
                    .setFont(bold).setFontSize(11).setFontColor(DARK_BLUE)
                    .setMarginTop(15).setMarginBottom(5));

            Table hallTable = new Table(UnitValue.createPercentArray(new float[]{2.5f, 1, 1.5f, 1, 2}))
                    .useAllAvailableWidth().setBorder(new SolidBorder(BORDER_COLOR, 1));

            // Header
            hallTable.addHeaderCell(headerCell("Hall", bold));
            hallTable.addHeaderCell(headerCell("Students", bold));
            hallTable.addHeaderCell(headerCell("Adjacency Checks", bold));
            hallTable.addHeaderCell(headerCell("Violations", bold));
            hallTable.addHeaderCell(headerCell("Status", bold));

            for (IntegrityAuditService.HallAuditResult hall : report.hallResults()) {
                hallTable.addCell(dataCell(hall.hallName(), regular));
                hallTable.addCell(dataCell(String.valueOf(hall.studentCount()), regular).setTextAlignment(TextAlignment.CENTER));
                hallTable.addCell(dataCell(String.format("%,d", hall.adjacencyChecks()), regular).setTextAlignment(TextAlignment.CENTER));
                hallTable.addCell(dataCell(String.valueOf(hall.adjacencyViolations()), regular).setTextAlignment(TextAlignment.CENTER));

                String status = hall.adjacencyViolations() == 0 ? "✓ PASS" : "✗ FAIL";
                DeviceRgb statusColor = hall.adjacencyViolations() == 0 ? SUCCESS_GREEN : FAIL_RED;
                hallTable.addCell(new Cell()
                        .add(new Paragraph(status).setFont(bold).setFontSize(9).setFontColor(statusColor)
                                .setTextAlignment(TextAlignment.CENTER))
                        .setPadding(5).setBorder(new SolidBorder(BORDER_COLOR, 0.5f)));
            }
            doc.add(hallTable);

            // ==================== VIOLATION DETAILS (when < 100%) ====================
            if (!report.certified()) {
                doc.add(new Paragraph("⚠ VIOLATION DETAILS — ACTION REQUIRED")
                        .setFont(bold).setFontSize(11).setFontColor(FAIL_RED)
                        .setMarginTop(15).setMarginBottom(5));

                doc.add(new Paragraph(
                        "The following halls have subject adjacency violations that need to be resolved. " +
                        "Navigate to each hall in HallSync, click Edit, and swap the flagged students to fix the issues.")
                        .setFont(regular).setFontSize(8).setFontColor(ColorConstants.DARK_GRAY)
                        .setTextAlignment(TextAlignment.JUSTIFIED).setMarginBottom(8));

                for (IntegrityAuditService.HallAuditResult hall : report.hallResults()) {
                    if (hall.adjacencyViolations() > 0) {
                        // Hall header
                        Table violationHeader = new Table(1).useAllAvailableWidth();
                        violationHeader.addCell(new Cell()
                                .add(new Paragraph(hall.hallName() + " — " + hall.adjacencyViolations() 
                                        + " violation(s) | " + hall.studentCount() + " students")
                                        .setFont(bold).setFontSize(9).setFontColor(ColorConstants.WHITE))
                                .setBackgroundColor(FAIL_RED).setPadding(5)
                                .setBorder(Border.NO_BORDER));
                        doc.add(violationHeader);

                        // Violation list
                        if (!hall.violationDetails().isEmpty()) {
                            Table detailTable = new Table(1).useAllAvailableWidth()
                                    .setBorder(new SolidBorder(BORDER_COLOR, 0.5f));
                            int maxDetails = Math.min(hall.violationDetails().size(), 10);
                            for (int i = 0; i < maxDetails; i++) {
                                detailTable.addCell(new Cell()
                                        .add(new Paragraph("• " + hall.violationDetails().get(i))
                                                .setFont(regular).setFontSize(7.5f).setFontColor(FAIL_RED))
                                        .setPadding(3).setBorder(new SolidBorder(BORDER_COLOR, 0.3f)));
                            }
                            if (hall.violationDetails().size() > 10) {
                                detailTable.addCell(new Cell()
                                        .add(new Paragraph("... and " + (hall.violationDetails().size() - 10) + " more violations")
                                                .setFont(italic).setFontSize(7).setFontColor(ColorConstants.GRAY))
                                        .setPadding(3).setBorder(new SolidBorder(BORDER_COLOR, 0.3f)));
                            }
                            doc.add(detailTable);
                        }
                    }
                }
            }

            // ==================== METHODOLOGY NOTE ====================
            doc.add(new Paragraph("VERIFICATION METHODOLOGY")
                    .setFont(bold).setFontSize(10).setFontColor(DARK_BLUE)
                    .setMarginTop(15).setMarginBottom(3));

            doc.add(new Paragraph(
                    "This certificate is generated by the HallSync Seating Allocation Engine (v1.1.0-ELITE). " +
                    "The system performs an exhaustive 6-directional adjacency analysis. For each student, " +
                    "the system verifies horizontal and diagonal separation. NOTE: Violations are flagged only " +
                    "if students from the SAME department sit together with the SAME subject code. " +
                    "Cross-department adjacency for common papers is certified as valid 'Class-wise Separation' " +
                    "and subject-separation logic is waived for dominant subjects (>50% of hall).")
                    .setFont(regular).setFontSize(8).setFontColor(ColorConstants.DARK_GRAY)
                    .setTextAlignment(TextAlignment.JUSTIFIED).setMarginBottom(10));

            doc.add(new Paragraph("Adjacency Directions Verified: ← → ↗ ↘ ↙ ↖ (Horizontal & Diagonal)")
                    .setFont(italic).setFontSize(8).setFontColor(BRAND_BLUE)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(15));

            // ==================== SIGNATURES ====================
            Table sigTable = new Table(UnitValue.createPercentArray(new float[]{1, 1, 1})).useAllAvailableWidth();
            sigTable.setMarginTop(30);

            sigTable.addCell(signatureCell("System Administrator", bold, regular));
            sigTable.addCell(signatureCell("Chief Superintendent", bold, regular));
            sigTable.addCell(signatureCell("Controller of Examinations", bold, regular));
            doc.add(sigTable);

            // ==================== FOOTER ====================
            doc.add(new Paragraph("— End of Integrity Certificate —")
                    .setFont(italic).setFontSize(8).setFontColor(ColorConstants.LIGHT_GRAY)
                    .setTextAlignment(TextAlignment.CENTER).setMarginTop(15));

            doc.add(new Paragraph("Generated: " + timestamp + " | Batch ID: " + report.batch().getId())
                    .setFont(regular).setFontSize(7).setFontColor(ColorConstants.LIGHT_GRAY)
                    .setTextAlignment(TextAlignment.CENTER).setMarginTop(2));

            doc.close();
            outStream.flush();

        } catch (Exception e) {
            throw new RuntimeException("Integrity Certificate PDF generation failed: " + e.getMessage(), e);
        }
    }

    // ==================== HELPER METHODS ====================

    private Cell detailCell(String label, String value, PdfFont bold, PdfFont regular) {
        return new Cell().setBorder(Border.NO_BORDER)
                .add(new Paragraph(label).setFont(bold).setFontSize(8).setFontColor(ColorConstants.GRAY).setMarginBottom(0))
                .add(new Paragraph(value).setFont(bold).setFontSize(11).setFontColor(DARK_BLUE))
                .setPadding(5).setTextAlignment(TextAlignment.CENTER);
    }

    private void addStatRow(Table table, String label, String value, PdfFont bold, PdfFont regular) {
        table.addCell(new Cell()
                .add(new Paragraph(label).setFont(regular).setFontSize(9).setFontColor(DARK_BLUE))
                .setPadding(6).setBorder(new SolidBorder(BORDER_COLOR, 0.5f)));
        table.addCell(new Cell()
                .add(new Paragraph(value).setFont(bold).setFontSize(10).setFontColor(DARK_BLUE)
                        .setTextAlignment(TextAlignment.RIGHT))
                .setPadding(6).setBorder(new SolidBorder(BORDER_COLOR, 0.5f)));
    }

    private Cell headerCell(String text, PdfFont bold) {
        return new Cell()
                .add(new Paragraph(text).setFont(bold).setFontSize(8).setFontColor(ColorConstants.WHITE)
                        .setTextAlignment(TextAlignment.CENTER))
                .setBackgroundColor(DARK_BLUE).setPadding(5)
                .setBorder(new SolidBorder(BORDER_COLOR, 0.5f));
    }

    private Cell dataCell(String text, PdfFont regular) {
        return new Cell()
                .add(new Paragraph(text).setFont(regular).setFontSize(9))
                .setPadding(5).setBorder(new SolidBorder(BORDER_COLOR, 0.5f));
    }

    private Cell signatureCell(String title, PdfFont bold, PdfFont regular) {
        return new Cell().setBorder(Border.NO_BORDER)
                .add(new Paragraph("___________________").setFont(regular).setFontSize(10)
                        .setTextAlignment(TextAlignment.CENTER).setMarginBottom(3))
                .add(new Paragraph(title).setFont(bold).setFontSize(8).setFontColor(DARK_BLUE)
                        .setTextAlignment(TextAlignment.CENTER));
    }

    private String resolveCollegeName() {
        String tenantId = com.exam.config.tenant.TenantContext.getCurrentTenant();
        if (tenantId == null) {
            return "EXAM SEATING ALLOCATION SYSTEM";
        }
        String cachedName = com.exam.config.tenant.TenantContext.getCollegeName(tenantId);
        if (cachedName != null && !cachedName.trim().isEmpty()) {
            return cachedName;
        }
        return "EXAM SEATING ALLOCATION SYSTEM";
    }
}
