package com.exam.parser.model;

public enum ParseErrorCode {
    EMPTY_PAGE,
    INSUFFICIENT_COLUMNS,
    AMBIGUOUS_REGISTER,
    MALFORMED_REGISTER,
    UNKNOWN_DEPARTMENT,
    MISSING_DEPARTMENT,
    BLANK_REGISTER,
    BLANK_DEPARTMENT,
    DUPLICATE_REGISTER,
    ZERO_STUDENTS,
    SINGLE_DEPARTMENT,
    CAPACITY_OVERFLOW,
    PAGE_BOUNDARY_STITCH,
    NOISE_OVERLAP
}
