CREATE TABLE IF NOT EXISTS lab_claim_records (
    id BIGSERIAL PRIMARY KEY,
    batch_id UUID,
    exam_date DATE,
    exam_season VARCHAR(100),
    session VARCHAR(50),
    department VARCHAR(100),
    semester VARCHAR(50),
    subject_code VARCHAR(50),
    subject_name VARCHAR(255),
    batch_number VARCHAR(100),
    registered_count INT DEFAULT 0,
    present_count INT DEFAULT 0,
    staff_name VARCHAR(255) NOT NULL,
    name_title VARCHAR(50),
    staff_role VARCHAR(100) NOT NULL,
    designation VARCHAR(100),
    institution_name VARCHAR(255),
    institution_code VARCHAR(50),
    mobile_no VARCHAR(50),
    bank_account_number VARCHAR(100),
    ifsc_code VARCHAR(50),
    bank_name VARCHAR(255),
    branch VARCHAR(255),
    distance_km NUMERIC(10, 2) DEFAULT 0.00,
    remuneration_amount NUMERIC(12, 2) DEFAULT 0.00,
    ta_amount NUMERIC(12, 2) DEFAULT 0.00,
    da_amount NUMERIC(12, 2) DEFAULT 0.00,
    total_amount NUMERIC(12, 2) DEFAULT 0.00,
    status VARCHAR(50) DEFAULT 'SUBMITTED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
