package com.exam.entity;

public enum AuditEventType {
    PREFLIGHT_FAILED,
    ALLOCATION_STARTED,
    SEASON_VIOLATION,
    DEADLOCK_RELAXED,
    TAIL_REBALANCED,
    ALLOCATION_COMPLETED,
    PDF_GENERATED,
    LOCK_ACQUIRED,
    LOCK_RELEASED,
    CONSECUTIVE_DEPT_ALLOWED,
    HALL_REUSE_ALLOWED,
    PATTERN_DEVIATION,
    SUBJECT_ADJACENCY_VIOLATION
}
