package com.exam.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    DUPLICATE_FILE,
    PREFLIGHT_FAILED,
    ALLOCATION_LOCKED,
    COOLDOWN_ACTIVE,
    RESOURCE_NOT_FOUND,
    QUEUE_FULL,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    METHOD_NOT_ALLOWED,
    MAIL_ERROR
}
